<?php

return [
    'public_routes' => [
        'POST:api/v1/identity/login',
        'POST:api/v1/identity/register',
        'POST:api/v1/identity/rotate-password',
        'GET:/',
        'POST:api/v1/payments/gateway/callback',
    ],
    'permissions' => [
        'GET:api/v1/recipes' => ['resource' => 'recipe', 'permission' => 'read'],
        'GET:api/v1/recipes/search' => ['resource' => 'recipe', 'permission' => 'read'],
        'POST:api/v1/recipes' => ['resource' => 'recipe', 'permission' => 'write'],
        'GET:api/v1/tags' => ['resource' => 'recipe', 'permission' => 'read'],
        'POST:api/v1/tags' => ['resource' => 'recipe', 'permission' => 'write'],
        'GET:api/v1/bookings' => ['resource' => 'booking', 'permission' => 'read'],
        'POST:api/v1/bookings' => ['resource' => 'booking', 'permission' => 'write'],
        'GET:api/v1/bookings/recipe' => ['resource' => 'booking', 'permission' => 'read'],
        'GET:api/v1/bookings/recipe/*' => ['resource' => 'booking', 'permission' => 'read'],
        'GET:api/v1/bookings/slot-capacity' => ['resource' => 'booking', 'permission' => 'read'],
        'GET:api/v1/bookings/today-pickups' => ['resource' => 'booking_ops', 'permission' => 'read'],
        'POST:api/v1/bookings/check-in' => ['resource' => 'booking_ops', 'permission' => 'write'],
        'POST:api/v1/bookings/no-show-sweep' => ['resource' => 'booking_ops', 'permission' => 'approve'],
        'GET:api/v1/bookings/*/dispatch-note' => ['resource' => 'booking_ops', 'permission' => 'read'],
        'GET:api/v1/bookings/pickup-points' => ['resource' => 'booking', 'permission' => 'read'],
        'GET:api/v1/pickup-points' => ['resource' => 'booking', 'permission' => 'read'],
        'GET:api/v1/operations/campaigns' => ['resource' => 'operations', 'permission' => 'read'],
        'POST:api/v1/operations/campaigns' => ['resource' => 'operations', 'permission' => 'write'],
        'GET:api/v1/operations/homepage-modules' => ['resource' => 'operations', 'permission' => 'read'],
        'POST:api/v1/operations/homepage-modules' => ['resource' => 'operations', 'permission' => 'write'],
        'GET:api/v1/operations/message-templates' => ['resource' => 'operations', 'permission' => 'read'],
        'POST:api/v1/operations/message-templates' => ['resource' => 'operations', 'permission' => 'write'],
        'GET:api/v1/operations/dashboard' => ['resource' => 'operations', 'permission' => 'read'],
        'GET:api/v1/payments' => ['resource' => 'payment', 'permission' => 'read'],
        'POST:api/v1/payments' => ['resource' => 'payment', 'permission' => 'write'],
        'GET:api/v1/payments/reconcile/batches' => ['resource' => 'payment', 'permission' => 'read'],
        'GET:api/v1/payments/reconcile/issues' => ['resource' => 'payment', 'permission' => 'read'],
        'POST:api/v1/payments/reconcile' => ['resource' => 'payment', 'permission' => 'approve'],
        'POST:api/v1/payments/gateway/orders' => ['resource' => 'payment', 'permission' => 'write'],
        'POST:api/v1/payments/gateway/auto-cancel' => ['resource' => 'payment', 'permission' => 'approve'],
        'POST:api/v1/payments/reconcile/daily' => ['resource' => 'payment', 'permission' => 'approve'],
        'POST:api/v1/payments/reconcile/repair' => ['resource' => 'payment', 'permission' => 'approve'],
        'POST:api/v1/payments/reconcile/close' => ['resource' => 'payment', 'permission' => 'approve'],
        'POST:api/v1/payments/reauth' => ['resource' => 'payment', 'permission' => 'approve'],
        'POST:api/v1/payments/refund' => ['resource' => 'payment', 'permission' => 'approve'],
        'POST:api/v1/payments/adjust' => ['resource' => 'payment', 'permission' => 'approve'],
        'GET:api/v1/notifications/events' => ['resource' => 'notification', 'permission' => 'read'],
        'POST:api/v1/notifications/events' => ['resource' => 'notification', 'permission' => 'write'],
        'POST:api/v1/notifications/preferences/opt-out' => ['resource' => 'notification', 'permission' => 'write'],
        'POST:api/v1/notifications/messages' => ['resource' => 'notification', 'permission' => 'write'],
        'GET:api/v1/notifications/inbox' => ['resource' => 'notification', 'permission' => 'read'],
        'POST:api/v1/notifications/messages/*/read' => ['resource' => 'notification', 'permission' => 'write'],
        'POST:api/v1/notifications/messages/*/click' => ['resource' => 'notification', 'permission' => 'write'],
        'GET:api/v1/notifications/analytics' => ['resource' => 'notification', 'permission' => 'read'],
        'GET:api/v1/files' => ['resource' => 'file', 'permission' => 'read'],
        'POST:api/v1/files/upload-base64' => ['resource' => 'file', 'permission' => 'write'],
        'GET:api/v1/files/download' => ['resource' => 'file', 'permission' => 'read'],
        'GET:api/v1/files/signed-url' => ['resource' => 'file', 'permission' => 'read'],
        'GET:api/v1/files/*/signed-url' => ['resource' => 'file', 'permission' => 'read'],
        'GET:api/v1/files/download/*' => ['resource' => 'file', 'permission' => 'read'],
        'POST:api/v1/files/cleanup' => ['resource' => 'file', 'permission' => 'approve'],
        'GET:api/v1/reporting/dashboard' => ['resource' => 'reporting', 'permission' => 'read'],
        'GET:api/v1/reporting/anomalies' => ['resource' => 'reporting', 'permission' => 'read'],
        'POST:api/v1/reporting/anomalies/generate' => ['resource' => 'reporting', 'permission' => 'write'],
        'GET:api/v1/reporting/exports/bookings-csv' => ['resource' => 'reporting', 'permission' => 'read'],
        'GET:api/v1/admin/users' => ['resource' => 'admin', 'permission' => 'read'],
        'GET:api/v1/admin/audit-logs' => ['resource' => 'admin', 'permission' => 'read'],
        'POST:api/v1/admin/reauth' => ['resource' => 'admin', 'permission' => 'approve'],
        'GET:api/v1/admin/roles' => ['resource' => 'admin', 'permission' => 'read'],
        'POST:api/v1/admin/roles' => ['resource' => 'admin', 'permission' => 'write'],
        'GET:api/v1/admin/permissions' => ['resource' => 'admin', 'permission' => 'read'],
        'GET:api/v1/admin/resources' => ['resource' => 'admin', 'permission' => 'read'],
        'POST:api/v1/admin/grants' => ['resource' => 'admin', 'permission' => 'approve'],
        'POST:api/v1/admin/user-roles' => ['resource' => 'admin', 'permission' => 'approve'],
        'POST:api/v1/admin/users/*/enable' => ['resource' => 'admin', 'permission' => 'approve'],
        'POST:api/v1/admin/users/*/disable' => ['resource' => 'admin', 'permission' => 'approve'],
        'POST:api/v1/admin/users/*/reset-password' => ['resource' => 'admin', 'permission' => 'approve'],
        'POST:api/v1/admin/users/*/scopes' => ['resource' => 'admin', 'permission' => 'approve'],
    ],
];
