ALTER TABLE users
  ADD COLUMN IF NOT EXISTS store_id BIGINT UNSIGNED NULL,
  ADD COLUMN IF NOT EXISTS warehouse_id BIGINT UNSIGNED NULL,
  ADD COLUMN IF NOT EXISTS department_id BIGINT UNSIGNED NULL,
  ADD COLUMN IF NOT EXISTS failed_login_attempts INT UNSIGNED NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS last_failed_login_at DATETIME NULL,
  ADD COLUMN IF NOT EXISTS locked_until DATETIME NULL;

ALTER TABLE recipes
  ADD COLUMN IF NOT EXISTS step_count INT UNSIGNED NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS difficulty ENUM('easy','medium','hard') NOT NULL DEFAULT 'easy',
  ADD COLUMN IF NOT EXISTS calories INT UNSIGNED NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS estimated_cost DECIMAL(10,2) NOT NULL DEFAULT 0.00,
  ADD COLUMN IF NOT EXISTS popularity_score INT UNSIGNED NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS store_id VARCHAR(60) NULL,
  ADD COLUMN IF NOT EXISTS warehouse_id VARCHAR(60) NULL,
  ADD COLUMN IF NOT EXISTS department_id VARCHAR(60) NULL;

ALTER TABLE bookings
  ADD COLUMN IF NOT EXISTS store_id VARCHAR(60) NULL,
  ADD COLUMN IF NOT EXISTS warehouse_id VARCHAR(60) NULL,
  ADD COLUMN IF NOT EXISTS department_id VARCHAR(60) NULL;

ALTER TABLE payments
  ADD COLUMN IF NOT EXISTS store_id VARCHAR(60) NULL,
  ADD COLUMN IF NOT EXISTS warehouse_id VARCHAR(60) NULL,
  ADD COLUMN IF NOT EXISTS department_id VARCHAR(60) NULL;

CREATE TABLE IF NOT EXISTS roles (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  code VARCHAR(50) NOT NULL UNIQUE,
  name VARCHAR(100) NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS permissions (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  code VARCHAR(50) NOT NULL UNIQUE,
  name VARCHAR(100) NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS resources (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  code VARCHAR(50) NOT NULL UNIQUE,
  name VARCHAR(100) NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS user_roles (
  user_id BIGINT UNSIGNED NOT NULL,
  role_id BIGINT UNSIGNED NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY(user_id, role_id)
);

CREATE TABLE IF NOT EXISTS role_permission_resources (
  role_id BIGINT UNSIGNED NOT NULL,
  permission_id BIGINT UNSIGNED NOT NULL,
  resource_id BIGINT UNSIGNED NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY(role_id, permission_id, resource_id)
);

CREATE TABLE IF NOT EXISTS user_data_scopes (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  user_id BIGINT UNSIGNED NOT NULL,
  scope_type ENUM('store','warehouse','department') NOT NULL,
  scope_value VARCHAR(60) NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY uk_user_scope (user_id, scope_type, scope_value)
);

CREATE TABLE IF NOT EXISTS auth_sessions (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  user_id BIGINT UNSIGNED NOT NULL,
  token_hash CHAR(64) NOT NULL UNIQUE,
  ip_address VARCHAR(45) NOT NULL,
  user_agent VARCHAR(255) NOT NULL,
  expires_at DATETIME NOT NULL,
  revoked_at DATETIME NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_auth_sessions_active (expires_at, revoked_at)
);

CREATE TABLE IF NOT EXISTS ingredients (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  display_name VARCHAR(120) NOT NULL,
  normalized_name VARCHAR(120) NOT NULL UNIQUE,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_ingredient_norm (normalized_name)
);

CREATE TABLE IF NOT EXISTS recipe_ingredients (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  recipe_id BIGINT UNSIGNED NOT NULL,
  ingredient_name VARCHAR(120) NOT NULL,
  ingredient_name_norm VARCHAR(120) NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_recipe_ingredient_norm (ingredient_name_norm, recipe_id)
);

CREATE TABLE IF NOT EXISTS recipe_cookware (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  recipe_id BIGINT UNSIGNED NOT NULL,
  cookware_norm VARCHAR(80) NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_recipe_cookware (cookware_norm, recipe_id)
);

CREATE TABLE IF NOT EXISTS recipe_allergens (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  recipe_id BIGINT UNSIGNED NOT NULL,
  allergen_norm VARCHAR(80) NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_recipe_allergen (allergen_norm, recipe_id)
);

CREATE TABLE IF NOT EXISTS search_synonyms (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  synonym VARCHAR(80) NOT NULL UNIQUE,
  canonical_term VARCHAR(80) NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_syn_canonical (canonical_term)
);
